### PR TITLE
[file_copy] Rewrite as a module

### LINKED ISSUE #284: File copy doesn't support ansible_ssh_common_args
https://github.com/ansible-collections/cisco.nxos/blob/0c6ec645db52382db84a71dfe7fc4ba26ab7f4ae/plugins/action/nxos_file_copy.py#L414

ansible_ssh_common_args is ignored because of the ssh command being hardcoded.  This was difficult to troubleshoot as well the error message didn't indicate where the session was stuck. Suggest adding outcome['error_data'] to the message.

### LINKED ISSUE #337: NXOS_FILE_COPY: After 23 attempts, failed to spawn pexpect session error message for copying file using nxos_file_copy
##### SUMMARY

I was trying to copy image file from ftp server to nexus9k device. I have used nxos_file_copy module for this task. When I tried to execute this task either from AWX template or ansible-playbook, file is not getting copied to device. I'm getting below error on output.
{
"msg": "After 23 attempts, failed to spawn pexpect session to x.x.x.xBEFORE: None, AFTER: None",
"_ansible_no_log": false
}

In device, I'm not seeing any errors, nor connection attempts.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

nxos_file_copy

##### ANSIBLE VERSION

```paste below
ansible 2.9.15
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['//root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Aug 18 2020, 08:33:21) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### COLLECTION VERSION

```paste below
cisco.nxos:1.4.1-dev9
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
default_jinja2_native(/etc/ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT

OS: RHEL 8.3
Nexus 9k: nxos.9.3.6.bin

##### STEPS TO REPRODUCE

```yaml
  - name: COPY OVER NXOS IMAGE
    nxos_file_copy:
      file_pull: True
      file_pull_protocol: ftp
      file_pull_timeout: 1200
      remote_file: "repo/{{ nxos_version }}"
      remote_scp_server: "{{ remote_ftp_server }}"
      remote_scp_server_user: "{{ remote_ftp_server_user }}"
      remote_scp_server_password: "{{ remote_ftp_server_password }}"
      vrf: "management"
```

##### EXPECTED RESULTS

File should be copied.

##### ACTUAL RESULTS

Getting non-descriptive error about pexpect.

```paste below
ansible-playbook -i ../hosts --vault-id ../vault_pass test.yml -e device_list="MYDEVICE" -vvvvv
ansible-playbook 2.9.15
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.6.8 (default, Aug 18 2020, 08:33:21) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
Using /etc/ansible/ansible.cfg as config file
Reading vault password file: ../vault_pass
setting up inventory plugins
host_list declined parsing /var/lib/awx/projects/hosts as it did not pass its verify_file() method
auto declined parsing /var/lib/awx/projects/hosts as it did not pass its verify_file() method
Parsed /var/lib/awx/projects/hosts inventory source with ini plugin
Loading callback plugin yaml of type stdout, v2.0 from /usr/lib/python3.6/site-packages/ansible/plugins/callback/yaml.py

PLAYBOOK: test.yml **********************************************************************************************
Positional arguments: test.yml
verbosity: 5
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/var/lib/awx/projects/hosts',)
extra_vars: ('device_list=MYDEVICE',)
vault_ids: ('../vault_pass',)
forks: 5
1 plays in test.yml

PLAY [Upload the firmware] **************************************************************************************
META: ran handlers
Found a vault_id (default) in the vaulttext
We have a secret associated with vault id (default), will try to use to decrypt /var/lib/awx/projects/group_vars/cisco/vault
Trying to use vault secret=(FileVaultSecret(filename='/var/lib/awx/projects/vault_pass')) id=default to decrypt /var/lib/awx/projects/group_vars/cisco/vault
Trying secret FileVaultSecret(filename='/var/lib/awx/projects/vault_pass') for vault_id=default
Decrypt of "b'/var/lib/awx/projects/group_vars/cisco/vault'" successful with secret=FileVaultSecret(filename='/var/lib/awx/projects/vault_pass') and vault_id=default
Found a vault_id (default) in the vaulttext
We have a secret associated with vault id (default), will try to use to decrypt /var/lib/awx/projects/upgrade_firmware/group_vars/cisco/vault
Trying to use vault secret=(FileVaultSecret(filename='/var/lib/awx/projects/vault_pass')) id=default to decrypt /var/lib/awx/projects/upgrade_firmware/group_vars/cisco/vault
Trying secret FileVaultSecret(filename='/var/lib/awx/projects/vault_pass') for vault_id=default
Decrypt of "b'/var/lib/awx/projects/upgrade_firmware/group_vars/cisco/vault'" successful with secret=FileVaultSecret(filename='/var/lib/awx/projects/vault_pass') and vault_id=default

TASK [CISCO - Copy firmware to MYDEVICE] *************************************************************
task path: /var/lib/awx/projects/upgrade_firmware/test.yml:6
Found a vault_id (default) in the vaulttext
We have a secret associated with vault id (default), will try to use to decrypt None
Trying to use vault secret=(FileVaultSecret(filename='/var/lib/awx/projects/vault_pass')) id=default to decrypt None
Trying secret FileVaultSecret(filename='/var/lib/awx/projects/vault_pass') for vault_id=default
Decrypt successful with secret=FileVaultSecret(filename='/var/lib/awx/projects/vault_pass') and vault_id=default
<X.X.X.X> attempting to start connection
<X.X.X.X> using connection plugin ansible.netcommon.network_cli
<X.X.X.X> local domain socket does not exist, starting it
<X.X.X.X> control socket path is /root/.ansible/pc/4e82cccd24
<X.X.X.X> local domain socket listeners started successfully
<X.X.X.X> loaded cliconf plugin ansible_collections.cisco.nxos.plugins.cliconf.nxos from path /root/.ansible/collections/ansible_collections/cisco/nxos/plugins/cliconf/nxos.py for network_os cisco.nxos.nxos
<X.X.X.X>
<X.X.X.X> local domain socket path is /root/.ansible/pc/4e82cccd24
fatal: [MYDEVICE]: FAILED! =>
  msg: 'After 23 attempts, failed to spawn pexpect session to X.X.X.XBEFORE: None, AFTER: None'

PLAY RECAP ******************************************************************************************************
MYDEVICE        : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

This is very loosely based on https://github.com/ansible/ansible/issues/70549, but rather seems to be affected by https://pexpect.readthedocs.io/en/stable/commonissues.html#threads

### LINKED ISSUE #387: nxos_file copy fail when facts are gathered
##### SUMMARY

The task is failing only if the facts are gathered.

##### ISSUE TYPE
- Bug Report

The transfer is failing when the facts are gathered first.
It is working fine if I reset the connection before transferring files.
But then, if I do that, if the transfer task is skipped it is the next task (the one after the transfer) that is failing similarly.

##### COMPONENT NAME

nxos_file_copy or network_cli

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.6]
```

##### COLLECTION VERSION

```paste below
cisco.nxos 2.7.0 
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(~/.ansible.cfg) = True
CACHE_PLUGIN_CONNECTION(~/.ansible.cfg) = ~/.ansible/tmp
CALLBACKS_ENABLED(~/.ansible.cfg) = ['profile_tasks']
COLLECTIONS_PATHS(~/.ansible.cfg) = ['~/my_ansible_project/.env/lib/python3.6/site-packages/ansible_collections']
COMMAND_WARNINGS(~/.ansible.cfg) = False
DEFAULT_GATHERING(~/.ansible.cfg) = explicit
DEFAULT_GATHER_SUBSET(~/.ansible.cfg) = ['network', 'hardware']
DEFAULT_GATHER_TIMEOUT(~/.ansible.cfg) = 120
DEFAULT_LOG_PATH(~/.ansible.cfg) = ~/.ansible/tmp/logs/ansible.log
DEFAULT_MODULE_PATH(~/.ansible.cfg) = ['~/my_ansible_project/.env/lib/python3.6/site-packages/ansible/modules']
DEFAULT_MODULE_UTILS_PATH(~/.ansible.cfg) = ['/usr/share/ansible/modules', '~/my_ansible_project/.env/lib/python3.6/site-packages/ansible/module_utils']
DEFAULT_STRATEGY_PLUGIN_PATH(~/.ansible.cfg) = ['/usr/share/ansible/plugins/mitogen-0.2.9/ansible_mitogen/plugins/strategy']
DEFAULT_TIMEOUT(~/.ansible.cfg) = 500
DEPRECATION_WARNINGS(~/.ansible.cfg) = False
HOST_KEY_CHECKING(~/.ansible.cfg) = False
NETWORK_GROUP_MODULES(~/.ansible.cfg) = ['eos', 'nxos', 'ios', 'iosxr', 'junos', 'vyos']
PARAMIKO_HOST_KEY_AUTO_ADD(~/.ansible.cfg) = True
PARAMIKO_LOOK_FOR_KEYS(~/.ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(~/.ansible.cfg) = 36000
PERSISTENT_CONNECT_RETRY_TIMEOUT(~/.ansible.cfg) = 30
PERSISTENT_CONNECT_TIMEOUT(~/.ansible.cfg) = 36000
RETRY_FILES_ENABLED(~/.ansible.cfg) = False
SYSTEM_WARNINGS(~/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

Rhel 8.4

##### STEPS TO REPRODUCE

```yaml
    - name: 0 Gather facts
      cisco.nxos.nxos_facts:
        gather_subset:
          - features
          - hardware

    # - name: 1 Reset ssh connection before file transfer
    #   meta: reset_connection

    - name: 2 transfer
      cisco.nxos.nxos_file_copy:
        local_file: '/tmp/testfic.txt'
        vrf: management
```

##### EXPECTED RESULTS

TASK [transfer] *****************************************************************************************************************************************************************
task path: playbook.yml:48
Saturday 13 November 2021  06:26:14 +0800 (0:00:00.089)       0:00:10.988 ***** 
Found a vault_id (default) in the vaulttext
We have a secret associated with vault id (default), will try to use to decrypt None
Trying to use vault secret=(FileVaultSecret(filename='vault_passwd_file')) id=default to decrypt None
Trying secret FileVaultSecret(filename='vault_passwd_file') for vault_id=default
Decrypt successful with secret=FileVaultSecret(filename='vault_passwd_file') and vault_id=default
Found a vault_id (default) in the vaulttext
We have a secret associated with vault id (default), will try to use to decrypt None
Trying to use vault secret=(FileVaultSecret(filename='vault_passwd_file')) id=default to decrypt None
Trying secret FileVaultSecret(filename='vault_passwd_file') for vault_id=default
Decrypt successful with secret=FileVaultSecret(filename='vault_passwd_file') and vault_id=default
Found a vault_id (default) in the vaulttext
We have a secret associated with vault id (default), will try to use to decrypt None
Trying to use vault secret=(FileVaultSecret(filename='vault_passwd_file')) id=default to decrypt None
Trying secret FileVaultSecret(filename='vault_passwd_file') for vault_id=default
Decrypt successful with secret=FileVaultSecret(filename='vault_passwd_file') and vault_id=default
Found a vault_id (default) in the vaulttext
We have a secret associated with vault id (default), will try to use to decrypt None
Trying to use vault secret=(FileVaultSecret(filename='vault_passwd_file')) id=default to decrypt None
Trying secret FileVaultSecret(filename='vault_passwd_file') for vault_id=default
Decrypt successful with secret=FileVaultSecret(filename='vault_passwd_file') and vault_id=default
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
redirecting (type: terminal) ansible.builtin.nxos to cisco.nxos.nxos
redirecting (type: cliconf) ansible.builtin.nxos to cisco.nxos.nxos
<10.64.74.131> attempting to start connection
<10.64.74.131> using connection plugin ansible.netcommon.network_cli
Found ansible-connection at path ~/ansible/.env/bin/ansible-connection
<10.64.74.131> local domain socket does not exist, starting it
<10.64.74.131> control socket path is ~/.ansible/pc/6b67884b2b
<10.64.74.131> redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
<10.64.74.131> Loading collection ansible.netcommon from ~/ansible/.env/lib/python3.6/site-packages/ansible_collections/ansible/netcommon
<10.64.74.131> redirecting (type: terminal) ansible.builtin.nxos to cisco.nxos.nxos
<10.64.74.131> Loading collection cisco.nxos from ~/ansible/.env/lib/python3.6/site-packages/ansible_collections/cisco/nxos
<10.64.74.131> redirecting (type: cliconf) ansible.builtin.nxos to cisco.nxos.nxos
<10.64.74.131> Found a vault_id (default) in the vaulttext
<10.64.74.131> We have a secret associated with vault id (default), will try to use to decrypt None
<10.64.74.131> Trying to use vault secret=(FileVaultSecret(filename='vault_passwd_file')) id=default to decrypt None
<10.64.74.131> Trying secret FileVaultSecret(filename='vault_passwd_file') for vault_id=default
<10.64.74.131> Decrypt successful with secret=FileVaultSecret(filename='vault_passwd_file') and vault_id=default
<10.64.74.131> Found a vault_id (default) in the vaulttext
<10.64.74.131> We have a secret associated with vault id (default), will try to use to decrypt None
<10.64.74.131> Trying to use vault secret=(FileVaultSecret(filename='vault_passwd_file')) id=default to decrypt None
<10.64.74.131> Trying secret FileVaultSecret(filename='vault_passwd_file') for vault_id=default
<10.64.74.131> Decrypt successful with secret=FileVaultSecret(filename='vault_passwd_file') and vault_id=default
<10.64.74.131> Found a vault_id (default) in the vaulttext
<10.64.74.131> We have a secret associated with vault id (default), will try to use to decrypt None
<10.64.74.131> Trying to use vault secret=(FileVaultSecret(filename='vault_passwd_file')) id=default to decrypt None
<10.64.74.131> Trying secret FileVaultSecret(filename='vault_passwd_file') for vault_id=default
<10.64.74.131> Decrypt successful with secret=FileVaultSecret(filename='vault_passwd_file') and vault_id=default
<10.64.74.131> Found a vault_id (default) in the vaulttext
<10.64.74.131> We have a secret associated with vault id (default), will try to use to decrypt None
<10.64.74.131> Trying to use vault secret=(FileVaultSecret(filename='vault_passwd_file')) id=default to decrypt None
<10.64.74.131> Trying secret FileVaultSecret(filename='vault_passwd_file') for vault_id=default
<10.64.74.131> Decrypt successful with secret=FileVaultSecret(filename='vault_passwd_file') and vault_id=default
<10.64.74.131> local domain socket listeners started successfully
<10.64.74.131> loaded cliconf plugin ansible_collections.cisco.nxos.plugins.cliconf.nxos from path ~/ansible/.env/lib/python3.6/site-packages/ansible_collections/cisco/nxos/plugins/cliconf/nxos.py for network_os nxos
<10.64.74.131> ssh type is set to paramiko
<10.64.74.131> 
<10.64.74.131> local domain socket path is ~/.ansible/pc/6b67884b2b
Found a vault_id (default) in the vaulttext
We have a secret associated with vault id (default), will try to use to decrypt None
Trying to use vault secret=(FileVaultSecret(filename='vault_passwd_file')) id=default to decrypt None
Trying secret FileVaultSecret(filename='vault_passwd_file') for vault_id=default
Decrypt successful with secret=FileVaultSecret(filename='vault_passwd_file') and vault_id=default
Found a vault_id (default) in the vaulttext
We have a secret associated with vault id (default), will try to use to decrypt None
Trying to use vault secret=(FileVaultSecret(filename='vault_passwd_file')) id=default to decrypt None
Trying secret FileVaultSecret(filename='vault_passwd_file') for vault_id=default
Decrypt successful with secret=FileVaultSecret(filename='vault_passwd_file') and vault_id=default
Found a vault_id (default) in the vaulttext
We have a secret associated with vault id (default), will try to use to decrypt None
Trying to use vault secret=(FileVaultSecret(filename='vault_passwd_file')) id=default to decrypt None
Trying secret FileVaultSecret(filename='vault_passwd_file') for vault_id=default
Decrypt successful with secret=FileVaultSecret(filename='vault_passwd_file') and vault_id=default
Found a vault_id (default) in the vaulttext
We have a secret associated with vault id (default), will try to use to decrypt None
Trying to use vault secret=(FileVaultSecret(filename='vault_passwd_file')) id=default to decrypt None
Trying secret FileVaultSecret(filename='vault_passwd_file') for vault_id=default
Decrypt successful with secret=FileVaultSecret(filename='vault_passwd_file') and vault_id=default
changed: [nce0rtolab02] => {
    "changed": true,
    "file_system": "bootflash:",
    "local_file": "/tmp/testfic.txt",
    "remote_file": "testfic.txt",
    "transfer_status": "Sent: File copied to remote device."
}
META: ran handlers
META: ran handlers

##### ACTUAL RESULTS

TASK [transfer] *****************************************************************************************************************************************************************
task path: playbook.yml:44
Saturday 13 November 2021  06:10:22 +0800 (0:00:10.926)       0:00:11.266 ***** 
Found a vault_id (default) in the vaulttext
We have a secret associated with vault id (default), will try to use to decrypt None
Trying to use vault secret=(FileVaultSecret(filename='/path_to_the_vaultpass')) id=default to decrypt None
Trying secret FileVaultSecret(filename='/path_to_the_vaultpass') for vault_id=default
Decrypt successful with secret=FileVaultSecret(filename='/path_to_the_vaultpass') and vault_id=default
Found a vault_id (default) in the vaulttext
We have a secret associated with vault id (default), will try to use to decrypt None
Trying to use vault secret=(FileVaultSecret(filename='/path_to_the_vaultpass')) id=default to decrypt None
Trying secret FileVaultSecret(filename='/path_to_the_vaultpass') for vault_id=default
Decrypt successful with secret=FileVaultSecret(filename='/path_to_the_vaultpass') and vault_id=default
Found a vault_id (default) in the vaulttext
We have a secret associated with vault id (default), will try to use to decrypt None
Trying to use vault secret=(FileVaultSecret(filename='/path_to_the_vaultpass')) id=default to decrypt None
Trying secret FileVaultSecret(filename='/path_to_the_vaultpass') for vault_id=default
Decrypt successful with secret=FileVaultSecret(filename='/path_to_the_vaultpass') and vault_id=default
Found a vault_id (default) in the vaulttext
We have a secret associated with vault id (default), will try to use to decrypt None
Trying to use vault secret=(FileVaultSecret(filename='/path_to_the_vaultpass')) id=default to decrypt None
Trying secret FileVaultSecret(filename='/path_to_the_vaultpass') for vault_id=default
Decrypt successful with secret=FileVaultSecret(filename='/path_to_the_vaultpass') and vault_id=default
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
redirecting (type: terminal) ansible.builtin.nxos to cisco.nxos.nxos
redirecting (type: cliconf) ansible.builtin.nxos to cisco.nxos.nxos
<ip_address> attempting to start connection
<ip_address> using connection plugin ansible.netcommon.network_cli
Found ansible-connection at path ~/.env/bin/ansible-connection
<ip_address> found existing local domain socket, using it!
<ip_address> invoked shell using ssh_type: paramiko
<ip_address> ssh connection done, setting terminal
<ip_address> loaded terminal plugin for network_os nxos
<ip_address> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<ip_address> firing event: on_open_shell()
<ip_address> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<ip_address> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<ip_address> ssh connection has completed successfully
<ip_address> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<ip_address> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<ip_address> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<ip_address> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<ip_address> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<ip_address> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<ip_address> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<ip_address> updating play_context for connection
<ip_address> 
<ip_address> local domain socket path is ~/.ansible/pc/e652485022
Found a vault_id (default) in the vaulttext
We have a secret associated with vault id (default), will try to use to decrypt None
Trying to use vault secret=(FileVaultSecret(filename='/path_to_the_vaultpass')) id=default to decrypt None
Trying secret FileVaultSecret(filename='/path_to_the_vaultpass') for vault_id=default
Decrypt successful with secret=FileVaultSecret(filename='/path_to_the_vaultpass') and vault_id=default
Found a vault_id (default) in the vaulttext
We have a secret associated with vault id (default), will try to use to decrypt None
Trying to use vault secret=(FileVaultSecret(filename='/path_to_the_vaultpass')) id=default to decrypt None
Trying secret FileVaultSecret(filename='/path_to_the_vaultpass') for vault_id=default
Decrypt successful with secret=FileVaultSecret(filename='/path_to_the_vaultpass') and vault_id=default
Found a vault_id (default) in the vaulttext
We have a secret associated with vault id (default), will try to use to decrypt None
Trying to use vault secret=(FileVaultSecret(filename='/path_to_the_vaultpass')) id=default to decrypt None
Trying secret FileVaultSecret(filename='/path_to_the_vaultpass') for vault_id=default
Decrypt successful with secret=FileVaultSecret(filename='/path_to_the_vaultpass') and vault_id=default
Found a vault_id (default) in the vaulttext
We have a secret associated with vault id (default), will try to use to decrypt None
Trying to use vault secret=(FileVaultSecret(filename='/path_to_the_vaultpass')) id=default to decrypt None
Trying secret FileVaultSecret(filename='/path_to_the_vaultpass') for vault_id=default
Decrypt successful with secret=FileVaultSecret(filename='/path_to_the_vaultpass') and vault_id=default
fatal: [hostname]: FAILED! => {
    "changed": true,
    "file_system": "bootflash:",
    "local_file": "/tmp/testfic.txt",
    "msg": "Exception received : Expected unicode or bytes, got {'__ansible_vault': '$ANSIBLE_VAULT;1.1;AES256\\somehash\\\\n'}",
    "remote_file": "testfic.txt",
    "transfer_status": "Sent: File copied to remote device."

```paste below

```

### PR DESCRIPTION
**Pull request by NilashishC**
##### SUMMARY
- Fixes #284 
- Fixes #387 
- Fixes #337

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
nxos_file_copy.py

### CODE REVIEW

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by feisa** [comment]
@NilashishC any update when this will be merged, we just ran into the issue

**Comment by NilashishC** [comment]
@feisa By the end of this month.

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Pull request merged**
