### PR TITLE
Fix for #46

### LINKED ISSUE #46: Cisco NXOS MDS Module Issue
Im attempting to manage Cisco MDS switches running m9100-s5ek9-kickstart-mz.8.4.1.bin code.
The issue I'm running into is piping into json doesn't work

sh version | json
^
% Incomplete command at '^' marker.

but piping into json native works

sh version | json native
{
"header_str": "Cisco Nexus Operating System (NX-OS) Software\nTAC support: http://www.cisco.com/tac\nDocuments: http://www.cisco.com/en/US/products/ps9372/tsd_products_support_series_home.html\nCopyright (c) 2002-2019, Cisco Systems, Inc. All rights reserved.\nThe copyr
ights to certain works contained herein are owned by\nother third parties and are used and distributed under license.\nSome parts of this software are covered under the GNU Public\nLicense. A copy of the license is available at\nhttp://www.gnu.org/licenses/gpl.html.\n",
"bios_ver_str": "2.1.17",
"loader_ver_str": "N/A",
"kickstart_ver_str": "8.4(1)",
"sys_ver_str": "8.4(1)",
"bios_cmpl_time": "01/08/14",
"kick_file_name": "bootflash:///m9100-s5ek9-kickstart-mz.8.4.1.bin",
"kick_cmpl_time": " 6/30/2019 23:00:00",
"kick_tmstmp": "06/15/2019 04:15:24",
"isan_file_name": "bootflash:///m9100-s5ek9-mz.8.4.1.bin",
"isan_cmpl_time": " 6/30/2019 23:00:00",
"isan_tmstmp": "06/15/2019 05:44:25",
"chassis_id": "MDS 9148S 16G 48 FC (1 Slot) Chassis",
"module_id": "2/4/8/16 Gbps FC/Supervisor",
"cpu_name": "Motorola, e500v2",
"memory": 4088640,
"mem_type": "kB",
"proc_board_id": "JAE202108JM",
"host_name": "test-sanmc001",
"bootflash_size": 4001760,
"kern_uptm_days": 79,
"kern_uptm_hrs": 2,
"kern_uptm_mins": 38,
"kern_uptm_secs": 19,
"rr_usecs": 897283,
"rr_ctime": "Sat Feb 15 16:12:52 2020",
"rr_reason": "Reset Requested by CLI command reload",
"rr_sys_ver": "8.4(1)",
"rr_service": "",
"manufacturer": "Cisco Systems, Inc."
}

Can we work to replace just the pipe to JSON to JSON native? This way all nxos modules work across all nxos switches

ISSUE TYPE
Bug Report
COMPONENT NAME
ansible cisco nxos modules

ANSIBLE VERSION
2.9

CONFIGURATION
OS / ENVIRONMENT
cisco nxos

### PR DESCRIPTION
**Pull request by srbharadwaj**
##### SUMMARY
Fixes #46 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
cli conf change for mds platform check

### CODE REVIEW

**Comment by NilashishC** [comment]
@srbharadwaj This patch seems to be breaking unit tests for nxos_config.

**Comment by srbharadwaj** [comment]
checking...

**Comment by NilashishC** [comment]
Linters seem to be failing for cliconf/nxos.py https://c3196c9f8e4e04c6fb3e-383ebfb72952afa284b18a4edc2b49a3.ssl.cf1.rackcdn.com/78/1928b46b2dc4e4cc4f44b81ff8833e238814fe34/check/ansible-tox-linters/4adf53a/job-output.html#l633

Did you run black==19.3b0 with line-length 79 before pushing?

**Comment by srbharadwaj** [comment]
> Linters seem to be failing for cliconf/nxos.py https://c3196c9f8e4e04c6fb3e-383ebfb72952afa284b18a4edc2b49a3.ssl.cf1.rackcdn.com/78/1928b46b2dc4e4cc4f44b81ff8833e238814fe34/check/ansible-tox-linters/4adf53a/job-output.html#l633
> 
> Did you run black==19.3b0 with line-length 79 before pushing?

ah.. forgot about this.. lets check how this commit goes..

**Pull request merged**
