### PR TITLE
Add state purged in nxos_interfaces

### PR DESCRIPTION
**Pull request by NilashishC**
Signed-off-by: NilashishC <nilashishchakraborty8@gmail.com>

##### SUMMARY
- Fixes https://github.com/ansible-collections/cisco.nxos/issues/84

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
nxos_interfaces.py

### CODE REVIEW

**Review by justjais — COMMENTED** [review]
Purge integration test can also be added, rest of the changes LGTM

**Comment by NilashishC** [comment]
@justjais Since this case can be verified with unit tests, I thought of skipping integration tests to avoid increased CI runtimes.

**Comment by justjais** [comment]
@NilashishC agreed, but purge is state which is part of smoke and sanity and we decided to cover smoke test scenarios under integration tests.

**Comment by NilashishC** [comment]
@justjais okay, I added integration tests.

**Review by justjais — APPROVED** [review]

**Pull request merged**
