### PR TITLE
Prevent traceback when parsing unexpected line

### PR DESCRIPTION
**Pull request by NilashishC**
Signed-off-by: NilashishC <nilashishchakraborty8@gmail.com>

##### SUMMARY
Note: This is a temporary fix to let existing options provided by this module work. Adding `bfd` support requires considerable rework of the existing code and will be done in a later release.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

nxos_static_routes.py

### CODE REVIEW

**Review by KB-perByte — APPROVED** [review]

**Comment by ashwini-mhatre** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by ashwini-mhatre** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Pull request merged**
