### PR TITLE
 Do not use `meta: end_play` to skip tests 

### PR DESCRIPTION
**Pull request by NilashishC**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1132

##### SUMMARY
- Skipping tests with `meta: end_play` causes the EE testing `site.yaml` playbook to abruptly end without testing all targets.

### CODE REVIEW

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Review by ashwini-mhatre — APPROVED** [review]

**Pull request merged**
