### PR TITLE
added l3_peer_router functionality + documentation + tests

### PR DESCRIPTION
**Pull request by loganbest**
##### SUMMARY

VPC module was missing a simple flag to enabling/disabling Layer 3 Peer Router functionality. I pretty much duplicated exactly how `peer_gw` bool is implemented and tested on nexus 5k and 9k's in my environment. 

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

nxos_vpc

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by loganbest** [comment]
recheck

**Comment by loganbest** [comment]
I don't understand why that fails randomly but had a 100% successful run once

**Comment by NilashishC** [comment]
@loganbest It is a CI infra issue on our end.

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
@loganbest The integration tests are consistently failing for following test case:
- https://github.com/ansible-collections/cisco.nxos/blob/main/tests/integration/targets/nxos_vpc/tests/common/sanity.yaml#L139-L144
(no layer3 peer-router\r\r\nERROR: Please enable peer-gateway before configuring this feature\r\n\rnxos-9kv-I5(config-vpc-domain)#)

-

**Comment by loganbest** [comment]
@NilashishC Do you have a link to which test is failing? the ansible/check is green and the only things I see failing in the non-voting integration tests are not related to my change it seems

**Comment by NilashishC** [comment]
@loganbest The integration test jobs for NX-OS are set to non-voting because of random flakiness in our CI. You must have noticed that all the *-scenario03 jobs have failed. That is where the nxos_vpc target is tested.

Here's the job output log from one of the scenario03 jobs: https://ab9543f5173227672f5f-50546db36105ea883c1501741b816920.ssl.cf1.rackcdn.com/316/41b047d0c447157bfacf84280f7b5dfffe2569cd/check/ansible-test-network-integration-nxos-cli-python36-scenario03/4828e1b/job-output.txt

You'd have to grep for "failed=1".

I was also able to reproduce the issue by running the nxos_vpc test locally against NX-OS 7.0.3.I5.1 and 9.3.6.

**Comment by Andersson007** [comment]
hi, is there any issue with this PR now?

**Comment by NilashishC** [comment]
> hi, is there any issue with this PR now?

Yes, the issue I specified in my previous comment needs to be addressed before we can merge this PR.

**Comment by Andersson007** [comment]
@NilashishC thanks for the info!
@loganbest could you please take a look at https://github.com/ansible-collections/cisco.nxos/pull/316#issuecomment-885409786 ?

**Review by NilashishC — CHANGES_REQUESTED** [review]
Review comments need to be addressed before we can merge this PR.

**Comment by NilashishC** [comment]
Closing this PR due to lack of activity.

**Pull request closed without merging**
