### PR TITLE
Add nxos_ospf_interfaces module

### LINKED ISSUE #105: nxos_ospf_interfaces resource module

### PR DESCRIPTION
**Pull request by NilashishC**
Signed-off-by: NilashishC <nilashishchakraborty8@gmail.com>

##### SUMMARY
- Fixes #105 
##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
nxos_ospf_interfaces.py

### CODE REVIEW

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
Unit test coverage:
```

Module | statements | missing | excluded | branches | partial | coverage
-------  | -------  |    -------  |    -------  |-------  |-------  |-------  |-------  

plugins/module_utils/network/nxos/argspec/ospf_interfaces/ospf_interfaces.py | 4 | 0 | 0 | 0 | 0 | 100%
plugins/module_utils/network/nxos/config/ospf_interfaces/ospf_interfaces.py | 81 | 0 | 0 | 56 | 0 | 100%
plugins/module_utils/network/nxos/facts/ospf_interfaces/ospf_interfaces.py | 31 | 1 | 0 | 10 | 0 | 98%
plugins/module_utils/network/nxos/rm_templates/ospf_interfaces.py | 18 | 0 | 0 | 6 | 0 | 100%
plugins/modules/nxos_ospf_interfaces.py | 14 | 1 | 0 | 2 | 1 | 88%
tests/unit/modules/network/nxos/test_nxos_ospf_interfaces.py | 175 | 0 | 0 | 0 | 0 | 100%

Total | 323 | 2 | 0 | 74 | 1 | 99%
```

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Review by justjais — APPROVED** [review]

**Pull request merged**
