### PR TITLE
add FQCN to M() references

### PR DESCRIPTION
**Pull request by bmillemathias**
##### SUMMARY

add FQCN to M() references
ansible-collections/overview#89

##### ISSUE TYPE
- Docs Pull Request

### CODE REVIEW

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by bmillemathias** [comment]
> Could you please add a changelog for this as well?

Done.

By the way there is a fragment file directly under [changelog](https://github.com/ansible-collections/cisco.nxos/tree/main/changelogs) directory, that's seems to be an error.

**Comment by NilashishC** [comment]
@bmillemathias you are correct, thanks for pointing it out. Do you mind moving it to the correct position? :)

**Comment by bmillemathias** [comment]
> 
> 
> @bmillemathias you are correct, thanks for pointing it out. Do you mind moving it to the correct position? :)

https://github.com/ansible-collections/cisco.nxos/pull/129

**Pull request merged**
