### PR TITLE
[WIP]Add testcases for libssh transport

### PR DESCRIPTION
**Pull request by ganeshrn**
Depends-On: https://github.com/ansible-collections/ansible.netcommon/pull/30

##### SUMMARY

*  Add test cases with ansible_network_cli_ssh_type set to libssh
   to test libssh connection plugin

##### ISSUE TYPE

- Feature Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by NilashishC** [comment]
recheck

**Comment by ganeshrn** [comment]
recheck

**Comment by ganeshrn** [comment]
recheck

**Comment by ganeshrn** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
As discussed, closing this PR for now.

**Pull request closed without merging**
