### PR TITLE
nxos_snmp_community: properly handle partial matches in community string

### PR DESCRIPTION
**Pull request by NilashishC**
Signed-off-by: NilashishC <nilashishchakraborty8@gmail.com>

##### SUMMARY
- Fixes https://github.com/ansible-collections/cisco.nxos/issues/203

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
nxos_snmp_community.py

### CODE REVIEW

**Comment by GomathiselviS** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Review by GomathiselviS — COMMENTED** [review]
Since we agreed upon increasing the coverage with unit tests, do you think , if  testing this fix with a unit testcase is possible?

**Comment by NilashishC** [comment]
@GomathiselviS This particular case cannot be verified through unit tests. The code change in this patch is related to the on-box "grep" functionality of the target device. `grep word-exp` ensures that we always fetch snmp communities that are an exact match, which is not the case with only `grep`.

**Review by GomathiselviS — APPROVED** [review]

**Pull request merged**
