### PR TITLE
Fix default vlan state overridden issue

### PR DESCRIPTION
**Pull request by mikewiebe**
##### SUMMARY
Fixes https://github.com/ansible-collections/cisco.nxos/issues/425

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
nxos_vlans

##### ADDITIONAL INFORMATION
This fix changes the fact gathering logic for handling the unstructured output that comes back for `vlan` to `vni` mapping.  The old logic did a check to see if the vlan number exists in the output which could easily match in cases where a match is not desired.  This was causing the default vlan to be changed if `1`  matched anything next to a `\n` character  in the output line

### CODE REVIEW

**Comment by goneri** [comment]
recheck

**Comment by mikewiebe** [comment]
@goneri and @NilashishC The ansible check error above does not seem to be related to my changes.

`ModuleNotFoundError: No module named 'markupsafe'`

Is this an infra issue?

**Comment by goneri** [comment]
This was a problem with ansible-2.11 and a  updated dependency. A fix has recently been pushed

**Comment by goneri** [comment]
recheck

**Comment by NilashishC** [comment]
All integration tests are still failing with NODE_FAILURE. This is currently being looked into.

**Comment by NilashishC** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
This is currently failing with:
```
2022-03-07 05:22:05.957797 | fedora-35 | ERROR: Found 9 validate-modules issue(s) which need to be resolved:
2022-03-07 05:22:05.957908 | fedora-35 | ERROR: plugins/cliconf/nxos.py:0:0: invalid-documentation: DOCUMENTATION.author: Invalid author for dictionary value @ data['author']. Got 'Ansible Networking Team'
2022-03-07 05:22:05.957964 | fedora-35 | ERROR: plugins/cliconf/nxos.py:0:0: invalid-documentation: DOCUMENTATION.cliconf: extra keys not allowed @ data['cliconf']. Got 'nxos'
2022-03-07 05:22:05.958013 | fedora-35 | ERROR: plugins/cliconf/nxos.py:0:0: invalid-documentation: DOCUMENTATION.name: required key not provided @ data['name']. Got None
2022-03-07 05:22:05.958124 | fedora-35 | ERROR: plugins/httpapi/nxos.py:0:0: invalid-documentation: DOCUMENTATION.author: Invalid author for dictionary value @ data['author']. Got 'Ansible Networking Team'
2022-03-07 05:22:05.958172 | fedora-35 | ERROR: plugins/httpapi/nxos.py:0:0: invalid-documentation: DOCUMENTATION.httpapi: extra keys not allowed @ data['httpapi']. Got 'nxos'
2022-03-07 05:22:05.958214 | fedora-35 | ERROR: plugins/httpapi/nxos.py:0:0: invalid-documentation: DOCUMENTATION.name: required key not provided @ data['name']. Got None
2022-03-07 05:22:05.958272 | fedora-35 | ERROR: plugins/netconf/nxos.py:0:0: invalid-documentation: DOCUMENTATION.author: Invalid author for dictionary value @ data['author']. Got 'Ansible Networking Team'
2022-03-07 05:22:05.958309 | fedora-35 | ERROR: plugins/netconf/nxos.py:0:0: invalid-documentation: DOCUMENTATION.name: required key not provided @ data['name']. Got None
2022-03-07 05:22:05.958362 | fedora-35 | ERROR: plugins/netconf/nxos.py:0:0: invalid-documentation: DOCUMENTATION.netconf: extra keys not allowed @ data['netconf']. Got 'nxos'
```

We're looking into it.

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Review by NilashishC — APPROVED** [review]

**Pull request merged**
