### PR TITLE
DNM: Enable testing with stable-2.9

### PR DESCRIPTION
**Pull request by NilashishC**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/465

Signed-off-by: NilashishC <nilashishchakraborty8@gmail.com>

### CODE REVIEW

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
First Result - https://github.com/ansible-collections/cisco.nxos/pull/64/checks?check_run_id=677753287

All green except 3rd job has multiple authentication timeouts.

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
Second run (with jobs set to 3) - https://github.com/ansible-collections/cisco.nxos/pull/64/checks?check_run_id=678351386

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
4th run https://github.com/ansible-collections/cisco.nxos/pull/64/checks?check_run_id=680397576

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Pull request closed without merging**
