### PR TITLE
Properly mask values of sensitive keys in module result

### PR DESCRIPTION
**Pull request by NilashishC**
Depends-On: https://github.com/ansible-collections/ansible.netcommon/pull/246

##### SUMMARY
- Pass current module object to validate_config() in order to update no_log_values list for proper masking.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
facts/ospf_interfaces.py
facts/bgp_global.py

### CODE REVIEW

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Review by rohitthakur2590 — APPROVED** [review]

**Pull request merged**
