### PR TITLE
[snmp_server] Add alias for community

### LINKED ISSUE #433: nxos_snmp_server communities.community is not consistent
##### SUMMARY
nxos_snmp_server uses `communities.community` for the community name, while other network resource modules use `communities.name` (`ios`, `iosxr`, etc.). Could we make this consistent across all network devices?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.nxos.nxos_snmp_server

##### ANSIBLE VERSION

```paste below
any
```

##### COLLECTION VERSION

```paste below
cisco.nxos 2.9.0
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- name: Configure SNMP
  hosts: all
  vars:
    cfg:            
      location: 'Virtual'
      communities:
        - name: Durham
          rw: true
        - name: ChapelHill
          rw: true  

  tasks:
    - name: Use SNMP resource module [Cisco IOS]
      cisco.ios.snmp_server:
        state: merged
        config: "{{ cfg }}"
      when: ansible_network_os == 'ios'

    - name: Use SNMP resource module [Cisco NX-OS]
      cisco.nxos.snmp_server:
        state: merged
        config: "{{ cfg }}"
      when: ansible_network_os == 'nxos'
```

##### EXPECTED RESULTS

I expect the above playbook to work without any changes

##### ACTUAL RESULTS

I would need to make a different config for each device, which defeats the purpose of network resource modules.

```paste below

```

### PR DESCRIPTION
**Pull request by NilashishC**
##### SUMMARY
Fixes #433 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
nxos_snmp_server.py

### CODE REVIEW

**Comment by NilashishC** [comment]
recheck

**Review by KB-perByte — APPROVED** [review]

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Pull request merged**
