### PR TITLE
[terminal] fix privilege escalation

### LINKED ISSUE #664: Cisco NXOS ansible module cannot run commands on NXOS Version 10.3
##### SUMMARY
We have cisco devices with NXOS version 10.3 , we are trying to run multiple commands via ansible module cisco.nxos 2.7.1 and getting repeated timeout errors , we are able to manually ssh into the devices and run those commands,
One of the commands we are facing issue is " show ip prefix-list"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Cisco.nxos.nxos_command

##### ANSIBLE VERSION
ansible [core 2.11.12]

cisco.nxos version 2.7.1

### PR DESCRIPTION
**Pull request by NilashishC**
##### SUMMARY
- Fix #664 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
terminal/nxos.py

### CODE REVIEW

**Comment by NilashishC** [comment]
cc @praveenramoorthy

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by praveenramoorthy** [comment]
@NilashishC thanks for the fix.  It works fine.

**Pull request merged**
