### PR TITLE
fix lacp interface facts parser for lacp mode

### PR DESCRIPTION
**Pull request by lordofire**
In the current lacp interface facts parser, it will parse "mode" directly for the lacp mode, which could conflict with configs like
`"switchport mode trunk"`. Add `"lacp mode"` as the conf arg parser to make the lacp mode parsing more accurate.

### CODE REVIEW

**Comment by NilashishC** [comment]
Hi @lordofire. Thanks a lot for identifying this issue and raising the PR. For getting this merged, we would need a changelog fragment that describes this bugfix. A test case for that covers this scenario would be much appreciated!

**Comment by lordofire** [comment]
Hi @NilashishC, thanks for your suggestion. I have added the changelog and an UT is added, but I'm not sure what is the typical way to run it. Do you have any suggestion? Thanks.

**Comment by NilashishC** [comment]
To run the unit test you can do `ansible-test units --python <python version> tests/unit/modules/network/nxos/<file>.py`.
However, I see some linter failures in the CI run. To fix these you'd need to do the following:
- `pip install black==19.3b0`
- `black --line-length 79 .` (from collection root)
- `tox -elinters .` to confirm that there are no linter failures.
- `ansible-test sanity --python <python version> --requirements` to confirm that there are no sanity failures.

**Comment by jianan-pony** [comment]
@NilashishC Thanks for your feedback. I have fixed the changelog and formatting issue, but seems like I could not get the ansible-test run correctly when building the docker image, where it failed at:
```
jiananwa@jiananwa-pony-pc:~/src/cisco.nxos$ ansible-test units --python 3.5 tests/unit/modules/network/nxos/test_nxos_lacp_interfaces.py 
Sending build context to Docker daemon  333.9MB
Step 1/8 : FROM debian:7.7
7.7: Pulling from library/debian
Image docker.io/library/debian:7.7 uses outdated schema1 manifest format. Please upgrade to a schema2 image for better future compatibility. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/
a3ed95caeb02: Pull complete 
ee48d0fb051e: Pull complete 
Digest: sha256:f85412064bed169eac597fdc9d08867d57b919abc827860ba8bdb6c400aad0e9
Status: Downloaded newer image for debian:7.7
 ---> 6d129b37ec3b
Step 2/8 : MAINTAINER Rob McQueen
 ---> Running in b33d8c64bdd0
Removing intermediate container b33d8c64bdd0
 ---> 7004753ac09e
Step 3/8 : RUN apt-get update && apt-get install -y   python-dev   python-virtualenv   sudo
 ---> Running in 024c0e7cecf2
Ign http://security.debian.org wheezy/updates Release.gpg
Ign http://security.debian.org wheezy/updates Release
Err http://security.debian.org wheezy/updates/main amd64 Packages
  
Ign http://http.debian.net wheezy Release.gpg
Err http://security.debian.org wheezy/updates/main amd64 Packages
  
Err http://security.debian.org wheezy/updates/main amd64 Packages
  
Err http://security.debian.org wheezy/updates/main amd64 Packages
  
Ign http://http.debian.net wheezy-updates Release.gpg
Err http://security.debian.org wheezy/updates/main amd64 Packages
  404  Not Found [IP: 151.101.0.204 80]
Ign http://http.debian.net wheezy Release
Ign http://http.debian.net wheezy-updates Release
Err http://http.debian.net wheezy/main amd64 Packages
  
Err http://http.debian.net wheezy-updates/main amd64 Packages
  
Err http://http.debian.net wheezy/main amd64 Packages
  
Err http://http.debian.net wheezy-updates/main amd64 Packages
  
Err http://http.debian.net wheezy/main amd64 Packages
  
Err http://http.debian.net wheezy-updates/main amd64 Packages
  
Err http://http.debian.net wheezy/main amd64 Packages
  
Err http://http.debian.net wheezy-updates/main amd64 Packages
  
Err http://http.debian.net wheezy/main amd64 Packages
  404  Not Found
Err http://http.debian.net wheezy-updates/main amd64 Packages
  404  Not Found
W: Failed to fetch http://security.debian.org/dists/wheezy/updates/main/binary-amd64/Packages  404  Not Found [IP: 151.101.0.204 80]

W: Failed to fetch http://http.debian.net/debian/dists/wheezy/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://http.debian.net/debian/dists/wheezy-updates/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update && apt-get install -y   python-dev   python-virtualenv   sudo' returned a non-zero code: 100
Traceback (most recent call last):
  File "/usr/local/bin/ansible-test", line 69, in <module>
    main(context)
  File "/usr/local/bin/ansible-test", line 45, in main
    '-t', DOCKER_CONTAINER, '.']
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker', 'build', '-t', 'testbox', '.']' returned non-zero exit status 100
```

Also, I saw there is another failure here `ansible-test-network-integration-nxos-cli-python36-scenario03 : NODE_FAILURE in 0s`, but the link I click into is empty somehow. Do you know what's going on? Is there anyway I could trigger this ci so that I could see how it performs? Thanks.

**Comment by lordofire** [comment]
@NilashishC Thanks for your feedback. I have fixed the changelog and formatting issue, but seems like I could not get the ansible-test run correctly when building the docker image, where it failed at:
```
jiananwa@jiananwa-pony-pc:~/src/cisco.nxos$ ansible-test units --python 3.5 tests/unit/modules/network/nxos/test_nxos_lacp_interfaces.py 
Sending build context to Docker daemon  333.9MB
Step 1/8 : FROM debian:7.7
7.7: Pulling from library/debian
Image docker.io/library/debian:7.7 uses outdated schema1 manifest format. Please upgrade to a schema2 image for better future compatibility. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/
a3ed95caeb02: Pull complete 
ee48d0fb051e: Pull complete 
Digest: sha256:f85412064bed169eac597fdc9d08867d57b919abc827860ba8bdb6c400aad0e9
Status: Downloaded newer image for debian:7.7
 ---> 6d129b37ec3b
Step 2/8 : MAINTAINER Rob McQueen
 ---> Running in b33d8c64bdd0
Removing intermediate container b33d8c64bdd0
 ---> 7004753ac09e
Step 3/8 : RUN apt-get update && apt-get install -y   python-dev   python-virtualenv   sudo
 ---> Running in 024c0e7cecf2
Ign http://security.debian.org wheezy/updates Release.gpg
Ign http://security.debian.org wheezy/updates Release
Err http://security.debian.org wheezy/updates/main amd64 Packages
  
Ign http://http.debian.net wheezy Release.gpg
Err http://security.debian.org wheezy/updates/main amd64 Packages
  
Err http://security.debian.org wheezy/updates/main amd64 Packages
  
Err http://security.debian.org wheezy/updates/main amd64 Packages
  
Ign http://http.debian.net wheezy-updates Release.gpg
Err http://security.debian.org wheezy/updates/main amd64 Packages
  404  Not Found [IP: 151.101.0.204 80]
Ign http://http.debian.net wheezy Release
Ign http://http.debian.net wheezy-updates Release
Err http://http.debian.net wheezy/main amd64 Packages
  
Err http://http.debian.net wheezy-updates/main amd64 Packages
  
Err http://http.debian.net wheezy/main amd64 Packages
  
Err http://http.debian.net wheezy-updates/main amd64 Packages
  
Err http://http.debian.net wheezy/main amd64 Packages
  
Err http://http.debian.net wheezy-updates/main amd64 Packages
  
Err http://http.debian.net wheezy/main amd64 Packages
  
Err http://http.debian.net wheezy-updates/main amd64 Packages
  
Err http://http.debian.net wheezy/main amd64 Packages
  404  Not Found
Err http://http.debian.net wheezy-updates/main amd64 Packages
  404  Not Found
W: Failed to fetch http://security.debian.org/dists/wheezy/updates/main/binary-amd64/Packages  404  Not Found [IP: 151.101.0.204 80]

W: Failed to fetch http://http.debian.net/debian/dists/wheezy/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://http.debian.net/debian/dists/wheezy-updates/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update && apt-get install -y   python-dev   python-virtualenv   sudo' returned a non-zero code: 100
Traceback (most recent call last):
  File "/usr/local/bin/ansible-test", line 69, in <module>
    main(context)
  File "/usr/local/bin/ansible-test", line 45, in main
    '-t', DOCKER_CONTAINER, '.']
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker', 'build', '-t', 'testbox', '.']' returned non-zero exit status 100
```

Also, I saw there is another failure here `ansible-test-network-integration-nxos-cli-python36-scenario03 : NODE_FAILURE in 0s`, but the link I click into is empty somehow. Do you know what's going on? Is there anyway I could trigger this ci so that I could see how it performs? Thanks.

**Comment by NilashishC** [comment]
Hi @lordofire. I can see all the checks in the recent CI run passed, except for the linters one. Here's the error: https://56ecc2edb10fb2f35b28-754b7d55dbf2f7d20fa51c0588bd53f5.ssl.cf5.rackcdn.com/164/b0846e6d0ab0e3db6112f38212edc668da08d853/check/ansible-tox-linters/de5da9b/job-output.html#l928.
You need to format the test file you added with `black -l 79`.

**Comment by jianan-pony** [comment]
Seems everything is passed now :) @NilashishC

**Comment by lordofire** [comment]
Seems everything passed now :) @NilashishC

**Review by NilashishC — APPROVED** [review]

**Comment by NilashishC** [comment]
@lordofire Thanks again for working on this! This change will be shipped with the upcoming v1.2.0 release.

**Comment by jianan-pony** [comment]
Thanks @NilashishC ! Btw, where I could find the release information on this plugin? Also, where I could find the version information of this plugin relative to ansible release itself? Thanks.

**Pull request merged**
