### PR TITLE
[facts] Updates for MDS platform

### PR DESCRIPTION
**Pull request by NilashishC**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1747

##### SUMMARY
- This patch allows `gather_network_resources: all` to work for NX-OS on MDS platform.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
nxos_facts.py

### CODE REVIEW

**Review by KB-perByte — APPROVED** [review]

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Pull request merged**
