### PR TITLE
Fix rendering of log_adjacency_changes commands

### LINKED ISSUE #151: cisco.nxos.nxos_ospfv2 is not idempotent
##### SUMMARY
The module is not idempotent. I don't see new changes being pushed but the module returns changed

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.nxos.nxos_ospfv2
##### ANSIBLE VERSION
[feisa@vmx-feisa01 ansible-network]$ ansible --version
ansible 2.9.13
  config file = /home/feisa/ansible-network/ansible.cfg
  configured module search path = ['/home/feisa/ansible-network/library']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

##### OS / ENVIRONMENT
rhel 8.2

##### STEPS TO REPRODUCE
```yaml
- name: Merge the provided configuration with the exisiting running configuration
  cisco.nxos.nxos_ospfv2:
    config:
      processes:
      - process_id: 100
        router_id: "10.{{ location_id }}.255.{{ loopback_ip }}"
        areas:
        - area_id: "0.0.0.{{ location_id }}"
          ranges:
          - prefix: "10.{{ location_id }}.0.0/16"
            not_advertise: false
        redistribute:
          - protocol: bgp
            id: 15047
            route_map: FROM_BGP
        bfd: yes
        log_adjacency_changes:
          log: yes
          detail: yes
        passive_interface:
          default: yes
  tags:
    - nxos-ospf
```

##### ACTUAL RESULTS
changed: [test-spinc002] => {
    "after": {
        "processes": [
            {
                "areas": [
                    {
                        "area_id": "0.0.0.4",
                        "ranges": [
                            {
                                "prefix": "10.4.0.0/16"
                            }
                        ]
                    }
                ],
                "bfd": true,
                "log_adjacency_changes": {
                    "log": true
                },
                "passive_interface": {
                    "default": true
                },
                "process_id": "100",
                "redistribute": [
                    {
                        "id": "15047",
                        "protocol": "bgp",
                        "route_map": "FROM_BGP"
                    }
                ],
                "router_id": "10.4.255.2"
            }
        ]
    },
    "before": {
        "processes": [
            {
                "areas": [
                    {
                        "area_id": "0.0.0.4",
                        "ranges": [
                            {
                                "prefix": "10.4.0.0/16"
                            }
                        ]
                    }
                ],
                "bfd": true,
                "log_adjacency_changes": {
                    "log": true
                },
                "passive_interface": {
                    "default": true
                },
                "process_id": "100",
                "redistribute": [
                    {
                        "id": "15047",
                        "protocol": "bgp",
                        "route_map": "FROM_BGP"
                    }
                ],
                "router_id": "10.4.255.2"
            }
        ]
    },
    "changed": true,
    "commands": [
        "router ospf 100",
        "log-adjacency-changes",
        "area 0.0.0.4 range 10.4.0.0/16"
    ],
    "invocation": {
        "module_args": {
            "config": {
                "processes": [
                    {
                        "areas": [
                            {
                                "area_id": "0.0.0.4",
                                "authentication": null,
                                "default_cost": null,
                                "filter_list": null,
                                "nssa": null,
                                "ranges": [
                                    {
                                        "cost": null,
                                        "not_advertise": false,
                                        "prefix": "10.4.0.0/16"
                                    }
                                ],
                                "stub": null
                            }
                        ],
                        "auto_cost": null,
                        "bfd": true,
                        "default_information": null,
                        "default_metric": null,
                        "distance": null,
                        "flush_routes": null,
                        "graceful_restart": null,
                        "isolate": null,
                        "log_adjacency_changes": {
                            "detail": true,
                            "log": true
                        },
                        "max_lsa": null,
                        "max_metric": null,
                        "maximum_paths": null,
                        "mpls": null,
                        "name_lookup": null,
                        "passive_interface": {
                            "default": true
                        },
                        "process_id": "100",
                        "redistribute": [
                            {
                                "id": "15047",
                                "protocol": "bgp",
                                "route_map": "FROM_BGP"
                            }
                        ],
                        "rfc1583compatibility": null,
                        "router_id": "10.4.255.2",
                        "shutdown": null,
                        "summary_address": null,
                        "table_map": null,
                        "timers": null,
                        "vrfs": null
                    }
                ]
            },
            "running_config": null,
            "state": "merged"
        }
    }
}

### LINKED ISSUE #152: cisco.nxos.nxos_ospfv2 logging detail option not working
##### SUMMARY
Im passing the logging adjacency detail parameter but it's not doing anything on the cli. I verified no errors 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.nxos.nxos_ospfv2
##### ANSIBLE VERSION
[feisa@vmx-feisa01 ansible-network]$ ansible --version
ansible 2.9.13
  config file = /home/feisa/ansible-network/ansible.cfg
  configured module search path = ['/home/feisa/ansible-network/library']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

##### OS / ENVIRONMENT
rhel 8.2

##### STEPS TO REPRODUCE

- name: Merge the provided configuration with the exisiting running configuration
  cisco.nxos.nxos_ospfv2:
    config:
      processes:
      - process_id: 100
        router_id: "10.{{ location_id }}.255.{{ loopback_ip }}"
        areas:
        - area_id: "0.0.0.{{ location_id }}"
          ranges:
          - prefix: "10.{{ location_id }}.0.0/16"
            not_advertise: false
        redistribute:
          - protocol: bgp
            id: 15047
            route_map: FROM_BGP
        bfd: yes
        log_adjacency_changes:
          log: yes
          detail: yes
        passive_interface:
          default: yes
  tags:
    - nxos-ospf

##### ACTUAL RESULTS

router ospf 100
  bfd
  router-id 10.4.255.2
  redistribute bgp 15047 route-map FROM_BGP
  log-adjacency-changes
  area 0.0.0.4 range 10.4.0.0/16
  passive-interface default

changed: [test-spinc002] => {
    "after": {
        "processes": [
            {
                "areas": [
                    {
                        "area_id": "0.0.0.4",
                        "ranges": [
                            {
                                "prefix": "10.4.0.0/16"
                            }
                        ]
                    }
                ],
                "bfd": true,
                "log_adjacency_changes": {
                    "log": true
                },
                "passive_interface": {
                    "default": true
                },
                "process_id": "100",
                "redistribute": [
                    {
                        "id": "15047",
                        "protocol": "bgp",
                        "route_map": "FROM_BGP"
                    }
                ],
                "router_id": "10.4.255.2"
            }
        ]
    },
    "before": {
        "processes": [
            {
                "areas": [
                    {
                        "area_id": "0.0.0.4",
                        "ranges": [
                            {
                                "prefix": "10.4.0.0/16"
                            }
                        ]
                    }
                ],
                "bfd": true,
                "log_adjacency_changes": {
                    "log": true
                },
                "passive_interface": {
                    "default": true
                },
                "process_id": "100",
                "redistribute": [
                    {
                        "id": "15047",
                        "protocol": "bgp",
                        "route_map": "FROM_BGP"
                    }
                ],
                "router_id": "10.4.255.2"
            }
        ]
    },
    "changed": true,
    "commands": [
        "router ospf 100",
        "log-adjacency-changes",
        "area 0.0.0.4 range 10.4.0.0/16"
    ],
    "invocation": {
        "module_args": {
            "config": {
                "processes": [
                    {
                        "areas": [
                            {
                                "area_id": "0.0.0.4",
                                "authentication": null,
                                "default_cost": null,
                                "filter_list": null,
                                "nssa": null,
                                "ranges": [
                                    {
                                        "cost": null,
                                        "not_advertise": false,
                                        "prefix": "10.4.0.0/16"
                                    }
                                ],
                                "stub": null
                            }
                        ],
                        "auto_cost": null,
                        "bfd": true,
                        "default_information": null,
                        "default_metric": null,
                        "distance": null,
                        "flush_routes": null,
                        "graceful_restart": null,
                        "isolate": null,
                        "log_adjacency_changes": {
                            "detail": true,
                            "log": true
                        },
                        "max_lsa": null,
                        "max_metric": null,
                        "maximum_paths": null,
                        "mpls": null,
                        "name_lookup": null,
                        "passive_interface": {
                            "default": true
                        },
                        "process_id": "100",
                        "redistribute": [
                            {
                                "id": "15047",
                                "protocol": "bgp",
                                "route_map": "FROM_BGP"
                            }
                        ],
                        "rfc1583compatibility": null,
                        "router_id": "10.4.255.2",
                        "shutdown": null,
                        "summary_address": null,
                        "table_map": null,
                        "timers": null,
                        "vrfs": null
                    }
                ]
            },
            "running_config": null,
            "state": "merged"
        }
    }
}

### PR DESCRIPTION
**Pull request by NilashishC**
Signed-off-by: NilashishC <nilashishchakraborty8@gmail.com>

##### SUMMARY
- Fixes #151
- Fixes #152 
- Correctly process `log_adjacency_changes` dict while computing commands.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
rm_templates/ospfv2.py

### CODE REVIEW

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Review by GomathiselviS — APPROVED** [review]
LGTM!

**Pull request merged**
