### PR TITLE
nxos_feature: Allow enabling fabric forwarding feature

### PR DESCRIPTION
**Pull request by NilashishC**
Signed-off-by: NilashishC <nilashishchakraborty8@gmail.com>

##### SUMMARY
- Fixes https://github.com/ansible-collections/cisco.nxos/issues/213
- `fabric forwarding` doesn't show up in the output of `show feature` but is a configurable feature.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
nxos_feature.py

### CODE REVIEW

**Comment by NilashishC** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Review by GomathiselviS — APPROVED** [review]

**Pull request merged**
