### PR TITLE
Fix var-spacing rule from ansible-lint

### PR DESCRIPTION
**Pull request by ssbarnea**
##### SUMMARY

Reference: https://ansible-lint.readthedocs.io/en/latest/default_rules/#var-spacing

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by NilashishC** [comment]
recheck

**Review by NilashishC — CHANGES_REQUESTED** [review]
@ssbarnea Thanks for the PR! Could you please add a trivial changelog to this so that CI can pass?

**Comment by ssbarnea** [comment]
TBH, I do not think that this kind of change needs a changelog and I do not know how to tell it that changelog is not needed.

@cidrblock WDYT about that? Any idea if there is a special label or keyword we can add to description to disable that feature? -- similar to `skip-changelog` on devtools projects?

**Comment by cidrblock** [comment]
I think this would do exactly that: https://github.com/ansible-network/github_actions/pull/18  Can you give it a quick review?

**Comment by ssbarnea** [comment]
@NilashishC Sorted! Now we can use the label to tell it to skip requiring a changelog.

**Review by NilashishC — APPROVED** [review]

**Pull request merged**
