### PR TITLE
Fix var-naming[no-reserved] lint errors

### PR DESCRIPTION
**Pull request by NilashishC**

### CODE REVIEW

**Review by KB-perByte — APPROVED** [review]

**Comment by NilashishC** [comment]
The `all_green` check fails because it expects all workflows to end with `success` and does not honour `skipped`, which is what resulted for the changelog test.

**Comment by KB-perByte** [comment]
This to be updated https://github.com/ansible-collections/cisco.ios/blob/def8fe19c94c37949c7a518e49dee11c72166456/.github/workflows/tests.yml#L49

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Pull request merged**
